sudo apt-get install gcc
sudo apt-get install g++
sudo apt-get install qt4-dev-tools
sudo apt-get install cmake
sudo apt-get install libc6-dev
sudo apt-get install g++-multilib
sudo apt-get install gsl-bin
sudo apt-get install libgsl0-dev
sudo apt-get install flex
sudo apt-get install bison
sudo apt-get install libfl-dev
sudo apt-get install tcpdump
sudo apt-get install sqlite
sudo apt-get install sqlite3
sudo apt-get install libsqlite3-dev
sudo apt-get install libxml2
sudo apt-get install libxml2-dev
sudo apt-get install libgtk2.0-0
sudo apt-get install libgtk2.0-dev
sudo apt-get install vtun
sudo apt-get install uncrustify
sudo apt-get install graphviz
sudo apt-get install imagemagick  
sudo apt-get install dia
sudo apt-get install libgoocanvas-dev
sudo apt-get install openmpi-bin
sudo apt-get install openmpi-common
sudo apt-get install openmpi-doc
sudo apt-get install libopenmpi-dev
sudo apt-get install gccxml
sudo apt-get install lxc
sudo apt-get install libcppunit-dev
sudo apt-get install libcppunit-doc
sudo apt-get install glibc-doc
sudo apt-get install gitk
sudo apt-get install qt4-dev-tools
sudo apt-get install cmake
sudo apt-get install libfftw3-dev
sudo apt-get install libpcap-dev
sudo apt-get install libpopt-dev
sudo apt-get install screen
sudo apt-get install eog
sudo apt-get install evince

